# Generated by Django 3.1.1 on 2020-09-28 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Dime time on which the object was last modified.', verbose_name='modified at')),
                ('name', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Boolean field to get active a product')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Dime time on which the object was last modified.', verbose_name='modified at')),
                ('name', models.CharField(max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='poroducts/pictures/market/', verbose_name='Store logo picture')),
                ('is_active', models.BooleanField(default=True, help_text='Boolean field to get active a market')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScrapingProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Dime time on which the object was last modified.', verbose_name='modified at')),
                ('name', models.CharField(max_length=255)),
                ('picture', models.ImageField(upload_to='products/pictures/market/', verbose_name='Store the image of the product scraped')),
                ('url', models.URLField()),
                ('price', models.FloatField()),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Boolean field to get active a market')),
                ('product', models.ForeignKey(help_text='Relationship from which product was scraped', on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('store', models.ForeignKey(help_text='Relationship from which store was scraped', on_delete=django.db.models.deletion.CASCADE, to='products.store')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
